# This is just a placeholder Cargo.toml for the frontend directory
# The actual frontend is a Node.js/React project
[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# This crate is actually empty - the real frontend is in the React app